### ISSUE TITLE
error when compiling with g++ 10.2.1-6 or clang++ 11

### ISSUE THREAD

**Issue by mladinox** [f1nalspace/final_game_tech#158] opened 2024-08-21 03:08 UTC
./final_platform_layer.h:2297:51: error: no match for ‘operator=’ (operand types are ‘fplVersionInfo’ and ‘<brace-enclosed initializer list>’)
 2297 | # define fpl__m_StructInit(type, ...) {__VA_ARGS__}

**Comment by f1nalspace** [comment] 2024-08-23 10:53
Please double-check if the compile error happens on the main branch and report back. Thanks!

**Comment by f1nalspace** [comment] 2024-11-23 07:19
Closed due to duplicate of #161

**Closed by f1nalspace** 2024-11-23 07:19 UTC
